### ISSUE TITLE
Problem combining qpcr mode with primer blast

### ISSUE THREAD

**Issue by wm75** [jonas-fuchs/varVAMP#33]
when trying to combine mode `qpcr` with `-db` I'm running into:

```
Traceback (most recent call last):
  File "/home/wolma/miniconda3/envs/varvamp/bin/varvamp", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wolma/miniconda3/envs/varvamp/lib/python3.11/site-packages/varvamp/command.py", line 554, in main
    probe_regions, final_schemes = qpcr_workflow(
                                   ^^^^^^^^^^^^^^
  File "/home/wolma/miniconda3/envs/varvamp/lib/python3.11/site-packages/varvamp/command.py", line 450, in qpcr_workflow
    query_path = blast.create_BLAST_query_qpcr(qpcr_scheme_candidates, data_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wolma/miniconda3/envs/varvamp/lib/python3.11/site-packages/varvamp/scripts/blast.py", line 62, in create_BLAST_query_qpcr
    name = f"{primer_type}_{qpcr_scheme_candidates[amp][primer_type][1]}_{qpcr_scheme_candidates[amp][primer_type][2]}"

KeyError: 'probe'
```

which, at first glance, looks like a rather generic error that wouldn't depend on exact inputs, but let me know if you need more details to reproduce this.

**Comment by jonas-fuchs** [comment]
Should be an easy fix. The problem is that I did a consistent naming for all primers which include changing probe to PROBE and it was not changed in that line of code.

**Comment by jonas-fuchs** [comment]
@wm75 can you check if the PR fixes the issue?

**Comment by wm75** [comment]
Yes, seems to fix it, and I haven't encountered any new errors with it either :-)
