### ISSUE TITLE
Combination of qPCR and BLAST db fails

### ISSUE THREAD

**Issue by elischberg** [jonas-fuchs/varVAMP#37]
```Traceback (most recent call last):
  File "/usr/local/tools/_conda/envs/mulled-v1-88ec11123572a51b245ba097dc0b273940132dc7e25597f386c2d705a3f21960/bin/varvamp", line 10, in <module>
    sys.exit(main())
  File "/usr/local/tools/_conda/envs/mulled-v1-88ec11123572a51b245ba097dc0b273940132dc7e25597f386c2d705a3f21960/lib/python3.10/site-packages/varvamp/command.py", line 557, in main
    probe_regions, final_schemes = qpcr_workflow(
  File "/usr/local/tools/_conda/envs/mulled-v1-88ec11123572a51b245ba097dc0b273940132dc7e25597f386c2d705a3f21960/lib/python3.10/site-packages/varvamp/command.py", line 455, in qpcr_workflow
    amplicons, off_target_amplicons = blast.primer_blast(
  File "/usr/local/tools/_conda/envs/mulled-v1-88ec11123572a51b245ba097dc0b273940132dc7e25597f386c2d705a3f21960/lib/python3.10/site-packages/varvamp/scripts/blast.py", line 240, in primer_blast
    off_target_amplicons, amplicons = predict_non_specific_amplicons(
  File "/usr/local/tools/_conda/envs/mulled-v1-88ec11123572a51b245ba097dc0b273940132dc7e25597f386c2d705a3f21960/lib/python3.10/site-packages/varvamp/scripts/blast.py", line 206, in predict_non_specific_amplicons
    amplicons[off_target]["penalty"][0] = amplicons[off_target]["penalty"][0] + config.BLAST_PENALTY
TypeError: 'float' object is not subscriptable```

**Comment by jonas-fuchs** [comment]
Does this happen with any dataset?

**Comment by elischberg** [comment]
It's working. (:
